---
- name: This sets up an httpd webserver
  hosts: web
  become: true
  tasks:

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
     policy: targeted
     state: permissive

  - name: configuration change 
    copy:
     src: /home/centos/httpd.conf
     dest: /etc/httpd/conf/httpd.conf

  - name: Restart service httpd, in all cases
    service:
     name: httpd
     state: restarted

  - name: Install apache packages
    yum:
      name: php
      state: present

  - name: copy php file
    copy:
     src: /home/centos/test.php
     dest: /var/www/html/

  - name: Restart service httpd, in all cases
    service:
     name: httpd
     state: restarted
