---
# remove index file in ubuntu
  - name: remove index file
    file:
     path: /var/www/html/index.html
     state: absent
    when:  ansible_os_family ==  "Debian"

# Intall Apache in Ubunutu mechine
  - name: git repo
    git:
     repo: 'https://github.com/naveenreddy2205/ecomm.git'
     dest: /var/www/html
     update: yes
     force: yes

# copyfile
  - name: Copy file
    copy:
     src: files/static.html
     dest: /var/www/html/test.html

# template file
  - name: template file
    template:
     src: templates/dynamic.j2
     dest: /var/www/html/dynamic.html

# cinfiguration file template file
  - name: configuration file
    template:
     src: templates/httpd.j2
     dest: /etc/httpd/conf/httpd.conf
    when:  ansible_os_family ==  "RedHat"
    notify:
      - Restart service httpd 
  
